# Vim aliases.
alias cv="cd ~/.config/nvim"
alias v="nvim"
alias vc="vrc"
alias vgit="vim ~/.gitconfig"
alias vham="vim ~/.hammerspoon/init.lua"
alias vi="nvim"
alias via="vim ~/.zsh/aliases.zsh"
alias vim="/usr/local/bin/nvim"
alias vip="vim ~/.config/nvim/plugins.vimrc"
alias viv="vim ~/.zsh/vim/aliases.zsh"
alias vpk="vim package.json"
alias vprez="vim ~/.zpreztorc"
alias vrc="vim ~/.config/nvim/init.vim"
alias vt="vim ~/.tmux.conf"
alias vz="vim ~/.zsh/zshrc"
