# Vim aliases.
alias vim="/usr/local/bin/nvim"
alias v="nvim"
alias vi="nvim"
alias vgit="vim ~/.gitconfig"
alias vham="vim ~/.hammerspoon/init.lua"
alias via="vim ~/.aliases"
alias vialias="vim ~/.aliases"
alias vpk="vim package.json"
alias vprez="vim ~/.zpreztorc"
alias vrc="vim ~/.config/nvim/init.vim"
alias vc="vim ~/.vimrc"
alias vz="vim ~/.zshrc"
alias vt="vim ~/.tmux.conf"
