# ============
# Vim aliases.
# ============
alias cv="cd ~/.config/nvim"
alias v="nvim"
alias vc="vrc"
alias vgit="vim ~/.gitconfig"
alias vham="vim ~/.hammerspoon/init.lua"
alias vi="nvim"
alias via="vim ~/.zsh/aliases.zsh"
alias vif="vim ~/.zsh/functions.zsh"
alias vim="/usr/local/bin/nvim"
alias vimap="vim ~/.config/nvim/mappings.vimrc"
alias vip="vim ~/.config/nvim/plugins.vimrc"
alias vipc="vim ~/.config/nvim/plugins-config.vimrc"
alias vir="vim README.md"
alias vis="vim ~/.secrets"
alias viv="vim ~/.zsh/vim/aliases.zsh"
alias vpk="vim package.json"
alias vprez="vim ~/.zpreztorc"
alias vrc="vim ~/.config/nvim/init.vim"
alias vt="vim ~/.tmux.conf"
alias vz="vim ~/.zsh/zshrc"
