#!/bin/zsh

# Shortcut to this dotfiles path is $ZSH
export ZSH=$HOME/.zsh

typeset -U config_files
local config_files=($HOME/.zsh/**/*.zsh)

# 1) Load zprezto configuration.
for file in ${(M)config_files:#*/zpreztorc.zsh}; do . $file; done
# 2) Load the path file(s).
for file in ${(M)config_files:#*/path.zsh}; do . $file; done

# 3) Initialize autocomplete here, otherwise functions won't be loaded.
autoload -U compinit; compinit

# 4) Load everything else.
# Next, every completion after autocomplete loads
for file in ${${config_files:#*/path.zsh}:#*/zpreztorc.zsh}; do . $file; done
for file in ${(M)config_files:#*/completion.zsh}; do . $file; done

unset config_files
