#!/bin/sh
#!/bin/bash

# ===========================================================
# Log commit messages as a 'highlight' in RescueTime Premium.
#
# To enable this hook:
# 1. Place this file in your project's .git/hooks directory and make sure its
#    name is `post-commit`.
# 2. Make sure it has executable permissions (chmod +x post-commit)
# 3. All commits will be automatically logged as highlight events.
# ===========================================================
notify_rescuetime() {
  # REQUIRED FIELDS - Today's date and commit message
  MESSAGE=$(git log -1 HEAD --pretty=format:%s)
  DATE_TODAY=$(date +'%Y-%m-%d %H:%M:%S')
  LABEL='code commit' # (optional)

  http post 'https://www.rescuetime.com/anapi/highlights_post' \
    key=="$RESCUETIME_API_KEY" \
    highlight_date=="$DATE_TODAY" \
    description=="$MESSAGE" \
    source=="$LABEL" \
    --body
}

git-hooks run "$0" "$@"
if hash gtm &>/dev/null; then
  gtm commit --yes || /usr/local/bin/gtm commit --yes
  git pushgtm >/dev/null 2>&1 &
fi

notify_rescuetime &>/dev/null
notify_rescuetime_exit_code=$?
if ! [ "$notify_rescuetime_exit_code" -eq '0' ]; then
  echo "Unable to update RescueTime."
fi

if test -e .git/hooks/ctags; then
  .git/hooks/ctags >/dev/null 2>&1 &
fi
