#!/usr/bin/env zsh

export ZSH=$HOME/.zsh
typeset -U config_files
config_files=($ZSH/**/*.zsh)

# 1) Load the path file(s).
for file in ${(M)config_files:#*/path.zsh}; do . $file; done

source $ZSH/prompt/config.zsh

# 2) Initialize antibody, a lightweight, git-based "plugin" manager.
if (hash antibody &>/dev/null); then
  source <(antibody init)
  antibody bundle < "$ZSH/antibody"
fi

# Hack to make zsh load more quickly by not regenerating completion data
# on every shell init.
autoload -Uz compinit
re_initialize=0
for match in $zcompdump*(.Nmh+24); do
  re_initialize=1
  break
done
if [ "$re_initialized" -eq "1" ]; then
  compinit
  # Update the timestamp on compdump file.
  compdump
else
  # Omit the check for new functions once we've updated today.
  compinit -C
fi

test -e $ZSH/utils/tinylogger.zsh && . $ZSH/utils/tinylogger.zsh

ulimit -n 8192

# 3) Load everything else. Order is important here for autocompletion to work.
for file in ${${config_files:#*/path.zsh}:#*/zpreztorc.zsh}; do . $file; done

for file in ${(M)config_files:#*/completions.zsh}; do . $file; done

fpath=( \
  /usr/local/share/zsh/site-functions \
  /usr/local/share/zsh-completions \
  ~/bin/zsh-completions \
  $fpath \
)
source $fpath

unset config_files

# Finally, cleanup $PATH to remove duplicates.
PATH=$(echo "$PATH" | awk -v RS=':' -v ORS=":" '!a[$1]++')
