#!/bin/zsh

export ZSH=$HOME/.zsh

export ZPLUG_HOME=/usr/local/opt/zplug
test -e $ZPLUG_HOME && . $ZPLUG_HOME/init.zsh

test -e $ZSH/utils/tinylogger.zsh && . $ZSH/utils/tinylogger.zsh

ulimit -n 2048

typeset -U config_files
config_files=($HOME/.zsh/**/*.zsh)

# 1) Load zprezto configuration.
for file in ${(M)config_files:#*/zpreztorc.zsh}; do . $file; done
# 2) Load the path file(s).
for file in ${(M)config_files:#*/path.zsh}; do . $file; done

# 3) Load everything else. Order is important here for autocompletion to work.
for file in ${${config_files:#*/path.zsh}:#*/zpreztorc.zsh}; do . $file; done
for file in ${(M)config_files:#*/completions.zsh}; do . $file; done

fpath=(/usr/local/share/zsh-completions ~/bin/zsh-completions $fpath)

# 4) Initialize autocomplete here, otherwise functions won't be loaded.
autoload -Uz compinit && compinit -i

unset config_files

compinit

# Finally, cleanup $PATH to remove duplicates.
PATH=$(echo "$PATH" | awk -v RS=':' -v ORS=":" '!a[$1]++')
